notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
  downstream:
    server: $$DOWNSTREAM_DRONE_SERVER
    repositories:
      - jbaptiste_cs/ctecsas-otrs
      - jbaptiste_cs/apukay-otrs
      - jbaptiste_cs/cachesimple-otrs

    token: $$DOWNSTREAM_DRONE_TOKEN
    when:
      event: push
      branch: otrs-4_0_x
      success: true
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs
    tag:
      - latest
      - $${BRANCH}-$${COMMIT:0:8}
      - 5.0.25-$${COMMIT:0:8}
    file: otrs/Dockerfile
    context: otrs
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  #Temporal fix while running on CentOS
  #storage_driver: vfs
#  dockerhub:
#      token: 34deefd6-0539-4650-adf5-8d9944846c2e
#      repo: juanluisbaptiste/otrs
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs-mariadb
    tag:
      - latest
      - $${BRANCH}-$${COMMIT:0:8}
    file: mariadb/Dockerfile
    context: mariadb
    load: docker/image-mariadb.tar
    environment:
      - DOCKER_LAUNCH_DEBUG=true
#  dockerhub:
#      token: 94fd83d7-b8d1-4353-8cfc-c248623b8799
#      repo: juanluisbaptiste/otrs-mariadb
# deploy:
#   docker:
#     username: $$DOCKER_USER
#     password: $$DOCKER_PASSWORD
#     email: $$DOCKER_EMAIL
#     repo:$$DOCKER_USER/otrs
#     when:
#       branch:  [master, otrs-4_0_x]
#   docker:
#     username: $$DOCKER_USER
#     password: $$DOCKER_PASSWORD
#     email: $$DOCKER_EMAIL
#     repo:$$DOCKER_USER/otrs-mariadb
#     when:
#       branch: [master, otrs-4_0_x]
