notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
  downstream:
    server: $$DOWNSTREAM_DRONE_SERVER
    repositories:
      - jbaptiste_cs/ctecsas-otrs
      - jbaptiste_cs/apukay-otrs
      - jbaptiste_cs/cachesimple-otrs

    token: $$DOWNSTREAM_DRONE_TOKEN
    when:
      event: push
      branch: master
      success: true
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs
    tag:
      - latest
      - $${OTRS_VERSION}-$${COMMIT:0:8}
    file: otrs/Dockerfile
    context: otrs
    load: docker/image-otrs.tar
    save:
      destination: docker/image-otrs.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  #Temporal fix while running on CentOS
  #storage_driver: vfs
  cache:
    mount:
      - docker/image-otrs.tar
#  dockerhub:
#      token: 34deefd6-0539-4650-adf5-8d9944846c2e
#      repo: juanluisbaptiste/otrs
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs-mariadb
    tag:
      - latest
      - $${OTRS_VERSION}-$$COMMIT
    file: mariadb/Dockerfile
    context: mariadb
    load: docker/image-mariadb.tar
    save:
      destination: docker/image-mariadb.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  cache:
    mount:
      - docker/image-mariadb.tar
#  dockerhub:
#      token: 94fd83d7-b8d1-4353-8cfc-c248623b8799
#      repo: juanluisbaptiste/otrs-mariadb
deploy:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo:$$DOCKER_USER/otrs
    when:
      branch:  [master, otrs-4_0_x]
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo:$$DOCKER_USER/otrs-mariadb
    when:
      branch: [master, otrs-4_0_x]
